Parameters:
  UUID:
    Type: String
    Description: A unique UUID for resource naming
  KeyPair:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

Resources:
  MinecraftServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-07761f3ae34c4478d 
      KeyName: !Ref KeyPair 
      SecurityGroupIds:
        - Ref: MinecraftSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install java-1.8.0 -y
          yum remove java-1.7.0-openjdk -y
          mkdir /minecraft
          cd /minecraft
          wget https://launcher.mojang.com/v1/objects/f1a0073671057f01aa843443fef34330281333ce/server.jar -O minecraft_server.jar
          echo "eula=true" > eula.txt
          java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui

  MinecraftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Minecraft server access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
