Parameters:
  UUID:
    Type: String
    Description: A unique UUID for resource naming
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

Resources:
  MinecraftServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      Name: !Sub "minecraft-server-${UUID}"
      InstanceType: t2.medium
      ImageId: ami-0abcdef1234567890
      KeyName: MyKeyPair
      SecurityGroupIds:
        - Ref: MinecraftSecurityGroup

  MinecraftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Name: !Sub "mincraft-server-security-group-${UUID}"
      GroupDescription: Allow Minecraft server access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0
