name: Deploy SAM Application

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy SAM Application
    runs-on: ubuntu-latest
    env:
      UUID: ''

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate UUID
        run: echo "UUID=$(uuidgen)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name "minecraft-${{ env.UUID }}" --capabilities CAPABILITY_IAM --parameter-overrides UUID=${{ env.UUID }} $KeyName=${{ secrets.KEY_NAME }}
